<a href="https://colab.research.google.com/github/kkktim/Colab/blob/master/Ch03.%20%EB%94%A5%EB%9F%AC%EB%8B%9D%20%EC%8B%A4%EC%8A%B5%20/%204_%EB%94%A5%EB%9F%AC%EB%8B%9D_CNN_%EB%AA%A8%EB%8D%B8_%ED%85%8C%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
"""
  날짜 : 2022/05/10
  이름 : 강태호
  내용 : 딥러닝 CNN 모델 실습
"""
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets.cifar10 import load_data
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import load_model
from keras.preprocessing.image import load_img, img_to_array
from PIL import Image
tf.__version__

'2.8.0'

In [3]:
#데이터 불러오기
(cifar_train_data, cifar_train_label), (cifar_test_data, cifar_test_label) = load_data()

170508288/170498071 [==============================] - 11s 0us/step


In [25]:
#모델학습을 위한 데이터 전처리(정규화)
cifar_train_data2 = cifar_train_data / 255
cifar_test_data2 = cifar_test_data / 255

cifar_train_data2[0]

array([[[0.23137255, 0.24313725, 0.24705882],
        [0.16862745, 0.18039216, 0.17647059],
        [0.19607843, 0.18823529, 0.16862745],
        ...,
        [0.61960784, 0.51764706, 0.42352941],
        [0.59607843, 0.49019608, 0.4       ],
        [0.58039216, 0.48627451, 0.40392157]],

       [[0.0627451 , 0.07843137, 0.07843137],
        [0.        , 0.        , 0.        ],
        [0.07058824, 0.03137255, 0.        ],
        ...,
        [0.48235294, 0.34509804, 0.21568627],
        [0.46666667, 0.3254902 , 0.19607843],
        [0.47843137, 0.34117647, 0.22352941]],

       [[0.09803922, 0.09411765, 0.08235294],
        [0.0627451 , 0.02745098, 0.        ],
        [0.19215686, 0.10588235, 0.03137255],
        ...,
        [0.4627451 , 0.32941176, 0.19607843],
        [0.47058824, 0.32941176, 0.19607843],
        [0.42745098, 0.28627451, 0.16470588]],

       ...,

       [[0.81568627, 0.66666667, 0.37647059],
        [0.78823529, 0.6       , 0.13333333],
        [0.77647059, 0

In [8]:
#데이터 라벨을 범주형(one-hot encoding)으로 변환
cifar_train_label2 = to_categorical(cifar_train_label)
cifar_test_label2 = to_categorical(cifar_test_label)
cifar_train_label2[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [9]:
#외부 학습 모델 불러오기
model = load_model('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/cifar_model.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 32)        9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 16, 16, 32)       0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 16, 16, 32)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 16, 16, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 16, 16, 64)        36928     
                                                        

In [10]:
#모델 테스트
result = model.evaluate(cifar_test_data2, cifar_test_label2)
result

313/313 [==============================] - 19s 60ms/step - loss: 0.7018 - acc: 0.7673


[0.7017500996589661, 0.767300009727478]

In [32]:
#이미지 로드 함수 정의
def load_image(filename):
  #load the image
  img = load_img(filename, target_size=(32, 32))
  #convert to array
  img = img_to_array(img)
  #reshape into a single example with 3 channels
  img = img.reshape(1, 32, 32, 3)
  #prepare pixel data
  img = img.astype('float32')
  img = img / 255.0
  return img

In [33]:
#이미지 테스트
img = load_image('/content/drive/MyDrive/파이썬 데이터 과학 실습/file/flog.jpg')
img

array([[[[1.        , 1.        , 0.9647059 ],
         [1.        , 1.        , 0.9647059 ],
         [1.        , 1.        , 0.972549  ],
         ...,
         [1.        , 1.        , 0.9843137 ],
         [0.98039216, 0.99607843, 0.99215686],
         [0.9843137 , 1.        , 1.        ]],

        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 0.99215686],
         [1.        , 1.        , 0.9843137 ],
         ...,
         [1.        , 0.99215686, 1.        ],
         [0.9882353 , 0.9882353 , 0.9882353 ],
         [0.9843137 , 1.        , 0.98039216]],

        [[1.        , 0.99215686, 1.        ],
         [1.        , 0.99607843, 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 0.9764706 , 0.99607843],
         [1.        , 1.        , 0.99215686],
         [0.9764706 , 1.        , 0.9490196 ]],

        ...,

        [[1.        , 0.99607843, 1.        ],
         [1.        , 0.9882353 , 1.        ]

In [35]:
#이미지 모델 테스트
result = model.predict(img)
result.round()

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32)